name: Rust CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: cargo test --all

  build:
    name: Build Release Binaries
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: binary-linux
            binary_path: target/release/BlackBox_CSV_Render
          - os: windows-latest
            artifact_name: binary-windows
            binary_path: target/release/BlackBox_CSV_Render.exe
          - os: macos-latest
            artifact_name: binary-macos
            binary_path: target/release/BlackBox_CSV_Render
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfontconfig1-dev libfreetype6-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install fontconfig freetype
      - name: Build release binary
        run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.binary_path }}
          overwrite: true
          if-no-files-found: error
